### ISSUE TITLE
Request bodies

### ISSUE THREAD

**Issue by kelunik** [NigelGreenway/reactive-slim#5]
Seems like it's using `php://input` as request body instead of the request body stream provided by ReactPHP. `php://input` is additionally a read-only stream.

https://github.com/NigelGreenway/reactive-slim/blob/701667b3c2b2538d2fe2eab9a0db3d09d4a36f4b/src/Server.php#L87

**Comment by NigelGreenway** [comment]
@kelunik I wasn't sure about the best practice on this as the `React\Http\Request` does not allow me to access the body, unless I am missing something?

**Comment by kelunik** [comment]
@NigelGreenway It's an event emitter that emits `"data"` events on body chunks, but I guess you have to buffer it yourself.

**Comment by NigelGreenway** [comment]
That makes sense, so I would do the following:

```php

$stream = new Stream('php://input', 'w')'

$request->on('data', function($body) use (&$stream) {
    $stream->write($body);
});

$stream->rewind();

// Hydrate new PSR7 Response object
```

**Comment by kelunik** [comment]
You'll need a readable stream for PSR-7, so not just `"w"` and in your example `$stream->rewind()` will be called before any data has been received. You'll need something like:

```php
$request->on("data", function ($chunk) use ($stream) {
    $stream->write($chunk);
});

$stream->on("end", function () use ($stream) {
    $stream->rewind();
    // dispatch
});
```

But if you use that, you always have to fully buffer any body. The ReactPHP guys might be able to tell you more.

The main problem is that PSR-7 has been designed for synchronous applications with blocking IO. It won't really work in an async context, no matter how hard you try it.

**Comment by NigelGreenway** [comment]
Hey @kelunik, can you check over this PR #10 as I _think_ I've sorted it but wondered if I am missing something as I'm trying to understand how this process works.. :smiley:
